# Theme settings
doks:
    baseurl: https://fhirlab.net/
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: FHIR Lab
            image:
        nav:
            - item_name: Home
              item_url: 'https://fhirlab.net/'
              external_url: true
            - item_name: CSIRO SSCP
              item_url: 'https://sscp.health/'
              external_url: true
            - item_name: Community
              item_url: 'https://chat.whatsapp.com/D7V2j7qLi31EuPmFCoyRC1'
              external_url: true
    footer:
        content:
            logo:
                text: FHIRLab
                image:
            copyright: Copyright &copy; 2025<br>All rights reserved.
        social_list:
            - network_name: CSIRO SSCP
              profile_url: 'https://sscp.health/'
            - network_name: WhatsApp
              profile_url: 'https://chat.whatsapp.com/D7V2j7qLi31EuPmFCoyRC1'
           # - network_name: youtube
           #   profile_url: 'https://www.youtube.com/@upmsilab'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
